import { Theme } from './symbols';

export const darkTheme: Theme = {
  name: 'standard-dark',
  properties: {
    '--background': '#242932',
    '--bannerFourColor': '#0cc285',
    '--bannerOneColor': '#182848',
    '--bannerTextColor': '#fff',
    '--bannerThreeColor': '#0cc285',
    '--bannerTwoColor': '#15a4fa',
    '--cardContentColor': 'rgba(107,183,240,0.15)',
    '--cardContentText': '#ffffff',
    '--cardHeaderColorBottom': '#2d3338',
    '--cardHeaderColorTop': '#205379',
    '--cardHeaderText': '#ffffff',
    '--cardOutline': '#073f4e',
    '--iconColor': '#03082c',
    '--navBarOverlay': 'rgba(21,32,41,0.45)',
    '--primaryAccent': '#15a4fa',
    '--primaryButtonColor': '#337AB7',
    '--primaryButtonText': '#fff',
    '--secondaryAccent': '#00ff2e',
    '--secondaryButtonColor': '#27B6AF',
    '--secondaryButtonText': '#fff',
    '--sidePanelBorderColor': 'rgba(191,217,224,0.15)',
    '--sidePanelBottomColor': '#2d3338',
    '--sidePanelHoverColor': '#234d6d',
    '--sidePanelSelectedColor': '#375065',
    '--sidePanelTextColor': '#ffffff',
    '--sidePanelTopColor': '#5a768a',
    '--tableEvenColor': '#F1F5F8',
    '--tableHeaderBottomColor': '#2d3338',
    '--tableHeaderTopColor': '#205379',
    '--tableOddColor': '#fff',
    '--textColor': '#ffffff',
    '--disabled': '#40547c'
  },
};
