import { Theme } from './symbols';

export const aquaLightTheme: Theme = {
  name: 'aqua-light',
  properties: {
    '--background': '#fff',
    '--bannerFourColor': '#0cc285',
    '--bannerOneColor': '#184845',
    '--bannerThreeColor': '#0cc2b8',
    '--bannerTwoColor': '#55c1bb',
    '--cardContentColor': '#fff',
    '--cardContentText': '#000',
    '--cardHeaderColorBottom': '#F8F9FC',
    '--cardHeaderColorTop': '#F8F9FC',
    '--cardHeaderText': '#768FE3',
    '--iconColor': '#1F2020',
    '--navBarOverlay': 'rgba(44,105,99,0.54)',
    '--primaryAccent': '#15a4fa',
    '--primaryButtonColor': '#337AB7',
    '--primaryButtonText': '#fff',
    '--secondaryAccent': '#fff',
    '--secondaryButtonColor': '#27B6AF',
    '--secondaryButtonText': '#fff',
    '--sidePanelBottomColor': 'rgba(93,199,123,0.26)',
    '--sidePanelHoverColor': 'rgba(122,215,109,0.17)',
    '--sidePanelSelectedColor': 'rgba(202,238,238,0.6)',
    '--sidePanelTextColor': '#152029',
    '--sidePanelTopColor': '#F1F5F8',
    '--tableEvenColor': '#F1F5F8',
    '--tableHeaderBottomColor': '#184845',
    '--tableHeaderTopColor': '#55c1bb',
    '--tableOddColor': '#fff',
    '--textColor': '#000',
    '--cardOutline': '#ddd',
    '--sidePanelBorderColor': '#fff',
    '--bannerTextColor': '#fff',
    '--disabled': '#C6C6C6',
  },
};
